# Generated by Django 3.2 on 2023-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='floorplan',
            field=models.FileField(blank=True, null=True, upload_to='floorplans/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='rendering',
            field=models.ImageField(blank=True, null=True, upload_to='renderings/'),
        ),
    ]
