# Generated by Django 3.2 on 2023-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20231107_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='half_baths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
