# Generated by Django 3.2 on 2024-05-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(blank=True, default='Raleigh', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='NC', max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, null=True)),
                ('image_front_landspace', models.ImageField(upload_to='community-images/')),
                ('image_front_portrait', models.ImageField(upload_to='community-images/')),
                ('active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address')),
            ],
        ),
    ]
