# Generated by Django 3.2 on 2024-05-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0002_plan_gallery'),
        ('address', '0001_initial'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homesite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Lot', 'LOT'), ('Available for presale', 'PRESALE'), ('Coming Soon', 'COMING_SOON'), ('Under Construction', 'UNDER_CONSTRUCTION'), ('Move-in Ready', 'MOVE_IN_READY')], default='Lot', max_length=50)),
                ('sale_status', models.CharField(choices=[('Available', 'AVAILABLE'), ('Under Contract', 'CONTRACT'), ('Reserved', 'RESERVED'), ('Sold', 'SOLD')], default='Available', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address')),
                ('construction_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_gallery', to='image.gallery')),
                ('listing_picture_landscape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_picture_landscape', to='image.image')),
                ('listing_picture_portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_picture_portrait', to='image.image')),
                ('lot_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_gallery', to='image.gallery')),
                ('move_in_ready_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_in_ready_gallery', to='image.gallery')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.plan')),
            ],
            options={
                'ordering': ['lot_number'],
            },
        ),
    ]
