# Generated by Django 3.2 on 2024-05-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20240515_1750'),
        ('homesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesite',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.community'),
        ),
    ]
