# Generated by Django 3.2 on 2023-11-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('plans', '0001_initial'),
        ('homesites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesite',
            name='community',
        ),
        migrations.AlterField(
            model_name='homesite',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='aerial_shot',
            field=models.ImageField(blank=True, null=True, upload_to='aerial_shots/'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='hidden',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='listing_picture',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='rendering',
            field=models.ImageField(blank=True, null=True, upload_to='renderings/'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('contract', 'Under Contract'), ('sold', 'Sold')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='status',
            field=models.CharField(blank=True, choices=[('presale', 'Available for Presale'), ('construction', 'Under Construction'), ('ready', 'Move-in Ready')], max_length=12, null=True),
        ),
    ]
