# Generated by Django 3.2 on 2023-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesites', '0002_auto_20231102_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesite',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
