# Generated by Django 3.2 on 2023-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesites', '0003_auto_20231102_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesite',
            options={'ordering': ['lot_number']},
        ),
        migrations.AlterField(
            model_name='homesite',
            name='lot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='status',
            field=models.CharField(blank=True, choices=[('presale', 'Available for Presale'), ('coming', 'Coming Soon'), ('construction', 'Under Construction'), ('ready', 'Move-in Ready')], max_length=12, null=True),
        ),
    ]
